##
## author jingwenyi create 2016.04.08 for test yuv
##

all:
#	g++ yuv_2_rgb.cpp yuv420pTorgb24.cpp -o yuv_2_rgb -lSDL
	arm-none-linux-gnueabi-g++ anyka_yuv_2_rgb.cpp yuv420pTorgb24.cpp -o anyka_yuv_2_rgb 

clean:
	rm -rf yuv_2_rgb
	rm -rf anyka_yuv_2_rgb
