


all:
	g++ main.cpp -o  print
	g++ frame_main.cpp -o audio_frame_test
	g++ cut_out_voice_data.cpp -o cut_out_voice
	g++ test_main.cpp  audio_analyses_algorithm.c -o algorithm_test


clean:
	rm -rf print
	rm -rf audio_frame_test
	rm -rf cut_out_voice
	rm -rf algorithm_test
