


all:
	arm-none-linux-gnueabi-g++  main.cpp   -o uart_test  -lpthread



clean:
	rm  -rf uart_test


install:
	cp uart_test  /home/anyka/jingwy/anyka39e/new/patch2_full/platform/rootfs/rootfs/usr/bin/
