##
## author jingwenyi create 2016.04.08 for test yuv
##
INCLUDES = -I include
SOURCE_FILE := \
	main_api_test.cpp \
	json_reader.cpp \
	json_value.cpp \
	json_writer.cpp \
	json_api.cpp 
	
TARGET := json_test

all:
	g++ ${SOURCE_FILE}  -o ${TARGET} ${INCLUDES}


clean:
	rm -rf ${TARGET}
